#define HUE_RED            0
#define HUE_RED_YELLOW    21
#define HUE_YELLOW        43
#define HUE_GREEN_YELLOW  64
#define HUE_GREEN         85
#define HUE_GREEN_CYAN   107
#define HUE_CYAN         128
#define HUE_BLUE_CYAN    149
#define HUE_BLUE         171
#define HUE_BLUE_MAGENTA 192
#define HUE_MAGENTA      213
#define HUE_RED_MAGENTA  235
